### ISSUE TITLE
The light/sound mask tab is not showing up in the lights config page

### ISSUE THREAD

**Issue by TheXeno30** [caewok/fvtt-light-mask#29]
The light/sound mask tab is not showing up in the lights config page. No console error. 

<img width="825" height="425" alt="Image" src="https://github.com/user-attachments/assets/df349d2d-3a5f-4be8-99e2-fb005879be1c" />

**Comment by TheXeno30** [comment]
can see it's set up be updated for v13 dnd 5.2, but it's still not showing up in the light source tab bar :)

**Comment by TheXeno30** [comment]
Foundryvtt: v13.351
DnD: 5.2.4

Med kun libwrapper og light/sound mask active it is still not showing up. Am i missing a setting somewhere?

<img width="652" height="357" alt="Image" src="https://github.com/user-attachments/assets/6fed0925-cd13-4726-b380-14e345c591c1" />

<img width="847" height="569" alt="Image" src="https://github.com/user-attachments/assets/bc8d8412-06ee-433c-87b2-65ad2276aba0" />

**Comment by caewok** [comment]
Fixed in v0.5.

**Comment by TheXeno30** [comment]
Nothing has changed - I still can't see the tab :)
running v13 and 5.2 still and on 0.92

**Comment by TheXeno30** [comment]
still on v13 and 5.2.x and on 0.92
