### ISSUE TITLE
Incorrect polygon if the emission angle is less than 360

### ISSUE THREAD

**Issue by dev7355608** [caewok/fvtt-light-mask#6]
The Light Mask modified algorithm produces incorrect results if the emission angle is less than 360. It already starts to fail at 359 in the demo below. No failure with Light Mask disabled.

![image](https://user-images.githubusercontent.com/31905376/159703779-01c9fa27-dce5-44de-86bf-55f5ab0f378e.png)

[fvtt-Scene-light-mask-bug.zip](https://github.com/caewok/fvtt-light-mask/files/8333122/fvtt-Scene-light-mask-bug.zip)

**Comment by dev7355608** [comment]
Reduced to one/two walls:

![image](https://user-images.githubusercontent.com/31905376/159706804-fa30e934-fbbf-4d9f-8c08-be2e65cab3f5.png)
![image](https://user-images.githubusercontent.com/31905376/159707035-2433f860-8751-4427-b121-e79c7abf42d2.png)

---

If the emission angle is set 350 with this one wall, the polygon is inverted:
![image](https://user-images.githubusercontent.com/31905376/159707322-7012e848-b104-4ca8-a02c-24b7d7fb7fd1.png)

**Comment by caewok** [comment]
Should be fixed by [v 0.2.0](https://github.com/caewok/fvtt-light-mask/releases/tag/0.2.0). Please re-open if you see errors. 

Note that you can still toggle on the polygon visualization using `CONFIG.debug.polygons = true` in the browser console. You can also check the new option to use the new sweep algorithm for all vision/light/sound in the settings for Light Mask to further explore where the algorithm might be failing, and then explore using any token/light/sound.

**Comment by dev7355608** [comment]
Still broken, but now in different way:

![lightmaskbug2](https://user-images.githubusercontent.com/31905376/167710704-3df16326-2877-4661-919e-b1546b0b727f.gif)

**Comment by caewok** [comment]
Yes, I see the issue. Might take a bit to track down, but I think I know what the problem is.

**Comment by caewok** [comment]
Fixed! 

https://user-images.githubusercontent.com/1267134/167741003-c368c4f8-dbde-40f9-a327-b2833d1f5765.mp4
